### ISSUE TITLE
Issue with setup_local.sh

### ISSUE THREAD

**Issue by skprasadu** [LexPredict/lexpredict-contraxsuite-deploy#9]
When I am running ./setup_local.sh | tee -a log.txt

I am getting below error, this is Ubuntu 16.04. I have followed all the instruction in README.md. Is there anything else I need to do.

$ systemctl restart elasticsearch ->
[localhost] out: sudo password:
[localhost] out: 

Done.
Disconnecting from localhost... done.
[localhost] Executing task 'git_clone'

$ mv /opt/lexpredict-contraxsuite /opt/lexpredict-contraxsuite.20171119 43318 ->
[localhost] out: mv: target '43318' is not a directory
[localhost] out: 

Warning: run() received nonzero return code 1 while executing 'mv /opt/lexpredict-contraxsuite /opt/lexpredict-contraxsuite.20171119 43318'!

Traceback (most recent call last):
  File "/home/krishna/my-applications/python/lexpredict-contraxsuite-deploy/ve/lib/python3.5/site-packages/fabric/main.py", line 762, in main

**Comment by skprasadu** [comment]
I got past that by changing as below in fabfile.py line 296,  run_check('mv {} "{}"'.format(repo_original_path, repo_backup_path))

After this, what is the next steps, I want to test few usecase, what commands I need to run to start UI. Can someone guide me?

**Comment by ericlex** [comment]
hello @skprasadu - Have you ran the installer as the root user or as a regular user like "ubuntu" that is the default on AWS? The errors suggest its being run as the root user. 

The installation script should be run as a regular user.

**Comment by skprasadu** [comment]
I am not running in AWS, I am running in my local ubuntu 16.04. I ran as regular user. I have different error now. In the virtualenv, I setup Jupyter, and was running document_model_tutorial.ipynb from lexpredict-contraxsuite/notebook-examples/ .

When I started to run this it asked me to install pandas, matplotlib, django after  that I was getting a weird  ImportError: No module named 'config' error.

When I was running,  
import django
from django.db import IntegrityError

# Setup django environment
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.local")
django.setup()

Is this permission issue?

**Comment by ericlex** [comment]
@skprasadu - Based on the messages you have shown, it looks like you need to activate a virtual environment for the project
`source /opt/ve/bin/activate`
and ensure all of the packages are installed (i.e. Django)

Next, you need to run migrations. i.e. in the activated virtual environment run
`python manage.py force_migrate`

After this, you should be able to run a notebook in the virtual environment - ve

Option#2 you can just activate the virtual environment where you ran `setup_local.sh`
(that file install ve by default)
and look into `setup_local.sh` and run commands from there partially
f.e. `fab -c local/fabricrc create_dirs`
and `fab -c local/fabricrc manage:force_migrate`

**Comment by skprasadu** [comment]
Now, I proceed, but I get strange error, 

At the ending steps, I get as follows, let me know if you get the solution:

[ec2-52-89-107-244.us-west-2.compute.amazonaws.com] out: if DEBUG_SQL:
[ec2-52-89-107-244.us-west-2.compute.amazonaws.com] out: NameError: name 'DEBUG_SQL' is not defined
[ec2-52-89-107-244.us-west-2.compute.amazonaws.com] out: > celery2@ip-172-31-23-195: * Child terminated with exit code 1
[ec2-52-89-107-244.us-west-2.compute.amazonaws.com] out: �[1;31mFAILED�[0m
[ec2-52-89-107-244.us-west-2.compute.amazonaws.com] out:

**Comment by ericlex** [comment]
Hello - I'll follow-up by email with you on this, but this looks like the error is related to missed steps from our install script `setup_local.sh`. It was interrupted on the step where some configuration files should be uploaded from
`templates` directory into target instance and at least `local_settings.py` was not uploaded properly
because `DEBUG_SQL=FALSE` settings is defined in that file

You would need to repeat the steps starting from uploading templates:
in activated virtual environment in `lexpredict-contraxsuite-deploy` folder run these commands from `setup_local.sh`:
```fab -c local/fabricrc upload_templates
fab -c local/fabricrc manage:force_migrate
fab -c local/fabricrc manage:set_site
fab -c local/fabricrc manage:collectstatic
fab -c local/fabricrc create_superuser
fab -c local/fabricrc nltk_download
fab -c local/fabricrc ssl_install
fab -c local/fabricrc start
```
It must be carefully monitored so that all five templates are loaded in the first fabric command including `local_settings.py` file. Finally if all commands went well, but the app is not started this command may help:
`fab -c local/fabricrc restart`

**Comment by tp-l** [comment]
Hi

I'm having the same error (with it exiting for DEBUG_SQL as not defined (1.0.3), or for "SECRET_KEY" setting not being defined (1.0.4).

In both cases these are defined in `local_settings.py`

I've tried the fix above in a virtual environment without success

[Log extracts.txt](https://github.com/LexPredict/lexpredict-contraxsuite-deploy/files/1533430/Log.extracts.txt)

**Comment by ericlex** [comment]
@tp-l - Thanks for raising. We will look into this further. Can you provide your entire log from the beginning of installation so we can have a bit more background information?

**Comment by tp-l** [comment]
Hi @ericlex - entire log is here: [6decinstalllog.txt](https://github.com/LexPredict/lexpredict-contraxsuite-deploy/files/1533885/6decinstalllog.txt)

Thanks again for your help

**Comment by ericlex** [comment]
@tp-l @skprasadu - In both of these cases we see the same issue: for some reason `local_settings.py` was not uploaded to target instance and uwsgi application throws errors because it cannot find some variables from there.
```
----------------
upload_templates
----------------
[localhost] put: <file obj> -> /home/##user##/run.sh
[localhost] put: <file obj> -> /usr/share/nginx/html/502.html
[localhost] put: <file obj> -> /etc/systemd/system/contrax_uwsgi.service
[localhost] put: <file obj> -> /etc/uwsgi/contrax_uwsgi.ini
Disconnecting from localhost... done.
```
So, you should repeat all steps described above. 

We've not been able to reproduce this issue on AWS or other environments after trying numerous times. We're considering refactoring the setup & installation a bit. What approach would be preferred for you? 

One thought we had is that perhaps we can change the first command from
```fab -c local/fabricrc upload_templates```
to upload only `local_settings.py`:
```fab -c local/fabricrc upload_template_and_reload:settings```
and then proceed with other commands to complete installation
